import React, { useState } from 'react';
import { Search, Globe, ChevronRight, Loader2, Link as LinkIcon } from 'lucide-react';

export const WebSearchApp: React.FC = () => {
    const [query, setQuery] = useState('');
    const [result, setResult] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);

    const handleSearch = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!query.trim()) return;

        setLoading(true);
        try {
            const res = await fetch(`/api/search?q=${encodeURIComponent(query)}`);
            const data = await res.json();
            setResult(data.answer);
        } catch (err) {
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="h-full flex flex-col bg-slate-950">
            {/* Header / Search Bar */}
            <div className="p-4 border-b border-white/5 bg-slate-900/50 flex flex-col gap-4">
                <div className="flex items-center gap-3">
                    <Globe size={18} className="text-blue-500" />
                    <h2 className="text-sm font-bold tracking-tight">Brave Explorer</h2>
                </div>
                <form onSubmit={handleSearch} className="relative">
                    <input
                        type="text"
                        value={query}
                        onChange={(e) => setQuery(e.target.value)}
                        placeholder="Search the real-time web..."
                        className="w-full bg-black/40 border border-white/10 rounded-lg py-2 pl-4 pr-10 text-sm focus:outline-none focus:border-blue-500/50 transition-colors font-mono"
                    />
                    <button type="submit" className="absolute right-2 top-1.5 p-1 hover:text-blue-500 transition-colors">
                        {loading ? <Loader2 size={16} className="animate-spin" /> : <Search size={16} />}
                    </button>
                </form>
            </div>

            {/* Results Area */}
            <div className="flex-1 overflow-y-auto p-6 font-mono selection:bg-blue-500/30">
                {result ? (
                    <div className="max-w-3xl mx-auto space-y-6">
                        <div className="flex items-center gap-2 text-xs text-muted-foreground uppercase tracking-widest mb-4">
                            <ChevronRight size={14} /> Result Generated by ChainMind Brain
                        </div>
                        <div className="text-sm leading-relaxed whitespace-pre-wrap text-blue-50/90 break-words">
                            {result}
                        </div>
                        <div className="pt-6 border-t border-white/5 flex items-center justify-between">
                            <span className="text-[10px] text-muted-foreground">Source: Brave Web Index</span>
                            <button className="flex items-center gap-1.5 text-[10px] font-bold text-blue-400 hover:text-blue-300">
                                <LinkIcon size={12} /> VIEW RAW SOURCES
                            </button>
                        </div>
                    </div>
                ) : (
                    <div className="h-full flex flex-col items-center justify-center text-center gap-4 opacity-30">
                        <Search size={48} />
                        <div className="max-w-xs">
                            <p className="text-sm font-bold uppercase tracking-widest mb-1">Knowledge Sync Active</p>
                            <p className="text-[10px]">Enter a query above to scan the BNB Chain ecosystem and beyond.</p>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};
